spring.application.name: api-gateway

server.port: 8080
eureka:
  client:
    service-url:
      defaultZone: https://curly-funicular-459grxq5rq5hj46v-8761.app.github.dev/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2

        - id: posts-service
          uri: lb://POSTS-SERVICE
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter
        - id: connections-service
          uri: lb://CONNECTIONS-SERVICE
          predicates:
            - Path=/api/v1/connections/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter

jwt:
  secretKey: NB2HI4DFONSWG33FOJXXE5LPNVZWKZLTORUGS3THNZTWC5DF

